# Small test config for debugging with GPU.
HPC_SLURM_ACCOUNT=abc  # Change this to your HPC account
HPC_SLURM_TIME=48:00:00
HPC_SLURM_NUM_NODES=250
HPC_SLURM_CPUS_PER_NODE=1
HPC_SLURM_MEM_PER_CPU=4GB
HPC_MASTER_WORKERS=4
